[package]
name = "pointer"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "../types" }
node = { path = "../node" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
