[package]
name = "sisi"
version = "0.1.0"
description = "A Tauri App"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde_json = "1.0"
log = "0.4"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = "2"
tauri-plugin-dialog = "2.6.0"
node = { path = "../crates/node" }
gateway = { path = "../crates/gateway" }
publisher = { path = "../crates/publisher" }
resolver = { path = "../crates/resolver" }
types = { path = "../crates/types" }
sisi-daemon = { path = "../crates/sisi-daemon" }
gossip = { path = "../crates/gossip" }
tokio = { workspace = true }
serde = { workspace = true }
ed25519-dalek = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
hex = { workspace = true }
tracing = { workspace = true }
dirs = { workspace = true }
