# syntax=docker/dockerfile:1
services:
  sisi-infra:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: sisi-infra
    restart: unless-stopped
    ports:
      - "6640:6640"
    environment:
      - RUST_LOG=info

  sisi-relay:
    image: docker.io/n0computer/iroh-relay:latest
    container_name: sisi-relay
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "7844:7844/udp"
    volumes:
      - ./relay.toml:/config/relay.toml:ro
      - relay-certs:/certs
    environment:
      - RUST_LOG=iroh_relay=info
    command: --config-path /config/relay.toml

  sisi-dns:
    image: docker.io/n0computer/iroh-dns-server:latest
    container_name: sisi-dns
    restart: unless-stopped
    ports:
      - "5353:5353/udp"
      - "8080:8080"
    volumes:
      - ./dns.toml:/config/dns.toml:ro
      - dns-data:/data
    environment:
      - RUST_LOG=info
    command: --config /config/dns.toml

volumes:
  relay-certs:
  dns-data:

