[relay]
hostname = "${RELAY_HOSTNAME}"
http_bind_addr = "0.0.0.0:80"
https_bind_addr = "0.0.0.0:443"

[tls]
cert_mode = "LetsEncrypt"
contact = "${ACME_CONTACT}"
cert_dir = "/certs"

[stun]
bind_addr = "0.0.0.0:3478"

[metrics]
bind_addr = "0.0.0.0:9090"
