[package]
name = "gossip"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "../types" }
node = { path = "../node" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
iroh-gossip = { workspace = true }
ulid = { workspace = true }
rusqlite = { workspace = true }
tokio-stream = { workspace = true }
sha2 = { workspace = true }
