[package]
name = "names"
version = "0.1.0"
edition = "2024"

[dependencies]
types = { path = "../types" }
node = { path = "../node" }
gossip = { path = "../gossip" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
rusqlite = { workspace = true }

[dev-dependencies]
getrandom = { workspace = true }
